### ISSUE TITLE
Delete Device Group, Device Type and Data Type explicitly

### ISSUE THREAD

**Issue by issb-gh** [alexstocker/sensorlogger#73]
If entries are created by registerDevice, they must also be deleted again.
It is important that only entries are deleted that do not violate the dependency rules.
Are there dependency rules?
I think one of them is:
No SensorDevice may be deleted if there are still log entries.
Although I would like to discuss this rule, the deleteDevice function already adheres to it.
The deleteDeviceType function will only delete a DeviceType if this type is no longer used by SensorDevices.
Similarly, the deleteDataType and deleteDeviceGroup functions will work.

**Comment by alexstocker** [comment]
Sounds good to me. That's how it should work. Have a look @wipeout placed in Device Sidebar.

https://github.com/alexstocker/sensorlogger/blob/0.1-devel/controller/sensorloggercontroller.php#L506

And no there are no foreignkey constraints set  due xml schema limitations. But this my change in future because with 0.1.0 SensorLogger switch to Migrations.

As long as no foreignkey constraints given we need to do checks like

https://github.com/alexstocker/sensorlogger/blob/0.1-devel/controller/sensorloggercontroller.php#L514

**Comment by alexstocker** [comment]
**DeviceTypes** and **DeviceGroups** are just used for grouping and categorizing a device. Therefore they can be deleted safely without any further check. 

**DataTypes** on the other hand **are related to** one ore more **devices**. So a **DataType** related to an **existing device** should be **never deleted**.

**Comment by alexstocker** [comment]
@issb-gh added your code. Thanx.
